name: Feature Request
description: Suggest an idea for Quick Field
labels:
  - enhancement
body:
  - type: textarea
    id: feature-description
    attributes:
      label: What would you like to see added to or changed in Quick Field, and why?
    validations:
      required: true
